require 'rspec'
require_relative '../src/character'
require_relative '../src/fighter'
require_relative '../src/rogue'
require_relative '../src/monk'

require_relative 'character_spec'
require_relative 'fighter_spec'
require_relative 'rogue_spec'
require_relative 'monk_spec'